var x, y;                                  
        y = 5;                                      
        x = y + 2;	                                
        console.log(x);                             
        x = y - 2;	                                
        console.log(x);                             
        x = y * 2;	                                
        console.log(x);                             
        x = y / 2;	                                
        console.log(x);                             
        x = y % 2;	                                
        console.log(x);                             
        let x2, y2;                                 
        y2 = 5;                                     
        x2 = y2 + 2;	                            
        console.log(x2);                            
        x2 = y2 - 2;	                            
        console.log(x2);                            
        x2 = y2 * 2;	                            
        console.log(x2);                            
        x2 = y2 / 2;	                            
        console.log(x2);                            
        x2 = y2 % 2;	                            
        console.log(x2);